import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header/page';
<<<<<<< HEAD
import Footer from '@/components/Footer/page'
=======
import Footer from "@/components/Footer/page";
>>>>>>> d39778004d0135a4bc614dcaa0afaba41007c95f


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <Header/>
        {children}
       <Footer/>
      
      </body>
        
=======
        <Header />
        {children}
        <Footer />

      </body>

>>>>>>> d39778004d0135a4bc614dcaa0afaba41007c95f
    </html>
  );
}
